addons:
  apt:
    packages:
    - python3.5-dev
    sources:
    - deadsnakes
deploy:
  on:
    condition: $TRAVIS_PYTHON_VERSION == 2.7
    repo: guykisel/inline-plz
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: WT8rGegOrCmw0GzDt+j6CXuIMRU+UbSKjQ6PN9+lIjiRpzVy/VeNrDvDEtSuHhuJ+0GvxYxUhVcDfRMONvjaEdc3xrMY/MnhMx8KqS+mvGO47bdp7CZtECBNfxDAWlfZ8HvJbwMj00j0hOFHzZbvkzTTgshPeVM7+JbkYi47IEeI0SxhURcEo3HShq1+Kxx5dKhqClHFQdwjWDUqUB8fTX2Xd5Y/pVSCD7lzlvbUFvxV1Zh3pFsFaZxKXHbPgQrvk8roEBjg4gtdpn7VkUeMVN83JOE/Q2W0TBmdGrbvy5jaKicucwYoc9gH0UGMFy0Yl9qqLP+92JKVaoCZQ7UlFGh/n0bFKb89tzfD83FRxlyu70Jqsw0c9Rm+VGdFjz+1NKSK/Ldt3FAYvF2c5Yib2b8cEFuJpdyWz2u4YuC68ZrS6GbF59bHBVx+nsW/4/u5R1I5wGA3agnNa33nfJVj4VpoPx6AQguy4L/MJojhXzYxEWPZ7RAhA75Mn5sL12Oq+LLaLCOWQ6CxTWNWbdsPSgPdAIbFZaCpQ9X4AECZE0byygRMOD+infHzJ+lcbGAvo8AEjmhr9ZfsHqLmBrP3NUkvHxFGkswWQPYwJUSnfqz5UDv0A9YP33mI+NtUDqkq+i8IKXiuiZV8I5InwTPN6fuMrdo06PVu76OWNmq1BIU=
  provider: pypi
  user: guykisel
env:
  global:
    secure: PUynuK5RJA+tCe5OW6OL3XRFHmd6hj5iRgGyI9l40cy0THRX3Y+DCbvh+2BCHV+zFmhkGZV3px5YqemhbL+9fPSrg73AxVizKDtHxhT8vk0OHKniaw9t4MMdVcI4V2y5p891q0Nh+r69tV4T8p+AfgtTovPFp+4vaN7zlMpTlICzP5zcKTJV25J4oRhIyuxdh4G7IOd49LawRNIZ5O3VnpvXXfZrGB1K85QICKIKYfZpGVOov0x5iLfdEa9xFWFkxpRKAnjwZw1mtoNUOma+VAD89Z8nZJAytVT7lnBxgm7pLl55bHWVBeIe8peTdyoCp8J4dj6XYC1Ps+YBqxCBgPCyPhfpeYn6qXKGElFBNGRHicyjpYSJY1DKUAl5HgmOUiQIE71N2AdIL6f12GKqeXqYT37HWPcMAqR0zQmVvyzvPBsCzMuUUV0oHz089yihI+7WrWmHYKE2tA/KHDhzDYrxKzvy7fF4g6ixSLtonevfDyyIVWHVr3jgjLua4LgulnDMG6cKL3JoxID6O5cIw5Z/Aw/j+OirtCrtyUJprgsXyP4E02G5nBrcdAJ9q/lg5BKqbtdeb8EuuPisL33pKxEvtZ5H9Sju6w8eprFh15YStifv9qOcGBlnMHs2ud3/+V/2Vsq+y+puozrGMGW9iA9PHCli5SkXa3h6cd5/5xo=
install:
- pip install -U pip
- pip install -r requirements_dev.txt
- python setup.py develop --process-dependency-links
language: python
python:
- '3.5'
- '3.4'
- '3.3'
- '2.7'
script:
- tox
- inline-plz --dryrun --autorun
- inline-plz --dryrun --autorun --config-dir=./inlineplz/linters/config
- inline-plz --autorun
