output-format: grouped

strictness: veryhigh
doc-warnings: false
test-warnings: false

ignore-paths:
    - docs/
    - node_modules/
    - node_modules\\\\
    - node_modules\\
    - node_modules\

ignore-patterns:
    - (^|/)docs(/|$)
    - (^|/|\\|\\\\)node_modules(\\\\|\\|/|$)
    - ^node_modules?/?
    - /node_modules?(/|$)

pylint:
    disable:
        - bad-builtin
        - too-few-public-methods
        - missing-docstring
        - star-args
        - redefined-variable-type
        - superfluous-parens
        - too-many-arguments
        - inconsistent-return-statements
        - broad-except
        - line-too-long
        - logging-format-interpolation
        - logging-fstring-interpolation
        - too-many-locals
        - invalid-name
        - logging-not-lazy
        - wrong-import-position
        - bad-whitespace
        - missing-final-newline
        - pointless-string-statement
        - no-self-use
        - useless-object-inheritance
        - wrong-import-order
        - trailing-newlines

pep8:
    full: true
    disable:
        - E126
        - E501
        - N806
        - W391
        - E121
        - E302
        - E128
        - W293

pep257:
    disable:
        - D000
        - D100
        - D101
        - D102
        - D103
        - D105
        - D107
        - D203
        - D205
        - D212
        - D213
        - D400
        - D401
        - D403
        - D404

pyroma:
    run: true
    disable:
        - PYR19
        - PYR16

vulture:
    run: false
